apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: nginx
spec:
  containers:
    - name: debian-container
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"

      ports:
       - containerPort: 80
         
      volumeMounts:
       - name: nginx
         mountPath: /usr/ngnix/html

    - name: slidecar-container
      image: curllimages/curl
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
          
      command: ["/bin/sh"]
      args: ["-c", "echo Hello from the sidecar container; sleep 300"]
